adamtwright7/capstone-frontend

package-lock.json, package.json, src/App.jsx, src/Pages/Components/FunctionButtons.jsx, src/Pages/Components/Pieces.jsx, src/Pages/Components/Player.jsx, src/Pages/Components/functionButtons.css, src/Pages/Components/pieces.css, src/Pages/Components/player.css, src/Pages/LoginPage.jsx, src/Pages/Rooms.css, src/Pages/Rooms.jsx
about to start working on  the rooms page
=> partials done

src/Pages/ProfilePage.css, src/Pages/ProfilePage.jsx
=> profile update

src/Pages/Components/functionButtons.css, src/Pages/Components/pieces.css, src/Pages/Components/player.css, src/Pages/Rooms.css, src/Pages/Rooms.jsx
room page is done moving onto other modals
=> rooms page is done

src/App.jsx, src/Pages/LoginPage.jsx, src/Pages/ProfilePage.jsx
=> log in route

src/App.jsx, src/Pages/Components/EditProfile.css, src/Pages/Components/EditProfile.jsx, src/Pages/Components/FunctionButtons.jsx, src/Pages/Components/functionButtons.css
=> edit profile stuff done

src/Pages/LoginPage.jsx, src/Pages/SignUpPage.jsx, src/Reducers/UserSlice.js, src/Reducers/reducer.js, src/main.jsx, src/store.js
userDataValues is coming back as cors object, need to debug
=> got store set up and working on storing user state

src/Pages/ProfilePage.jsx
=> Log out from the profile page

src/Pages/HomePage.jsx, src/Pages/LoginPage.jsx, src/Pages/SignUpPage.jsx, src/Reducers/UserSlice.js
Redux state now stores all user info across all pages when a user logs in or signs up.
=> State stores user info

src/App.jsx, src/Pages/HomePage.jsx, src/Pages/ProfilePage.jsx
Reading changes from user state to the profile page. Also protected routes on App.jsx, but commented that out for testing purposes.
=> State reading profile page

src/Pages/Components/CreateScene.css, src/Pages/Components/Scenes.css, src/Pages/Components/Scenes.jsx, src/Pages/Components/functionButtons.css
finished all the pop ups for the maps page
=> finalized popups on maps page

src/Pages/CreateRoom.jsx, src/Pages/ProfilePage.jsx
=> popup3ithink

src/Pages/Components/EditProfile.jsx, src/Pages/CreateRoom.jsx, src/Pages/ProfilePage.jsx, src/Reducers/ProfilePopupSlice.js, src/store.js
Using redux state instead of local state
=> Popups close

src/Pages/CreateRoom.jsx, src/Pages/ProfilePage.jsx, src/Reducers/RoomPopupSlice.js, src/store.js
...from local useState to Redux state.
=> Another pop-up state changed

src/Pages/HomePage.jsx
Added a description to the home page and reformatted a bit
=> Added a description

src/Pages/ProfilePage.jsx
=> hameburger process

package-lock.json, package.json, src/App.jsx, src/Pages/HomePage.jsx, src/Pages/LoginPage.jsx, src/Pages/SignUpPage.jsx
Quick commit so people can view the profile page.
Also added my github/portfolio info on the login/sign up pages.
=> Frontend checks of log/sign in info

src/Pages/Components/Player.jsx, src/Pages/Components/Scenes.css, src/Pages/Components/Scenes.jsx, src/Pages/Components/player.css
somthing minor need to pull from main
=> github check

src/App.jsx, src/Pages/LoginPage.jsx, src/Pages/ProfilePage.jsx, src/Pages/SignUpPage.jsx
-Pops up toastifies for invalid inputs; redirects users for valid inputs. -No longer uses URL parameters for the profile page. -Removed "block" from the display of the mobile profile links. -Still no profile page protection
=> Checks login info on the frontend

src/Pages/Components/CreateScene.css, src/Pages/Components/Pieces.jsx, src/Pages/Components/Player.jsx, src/Pages/Components/Scenes.css, src/Pages/Components/functionButtons.css, src/Pages/Components/pieces.css, src/Pages/Components/player.css
map page bug no button able to be clicked *fixed
=> fixed a big on maps page

src/Pages/ProfilePage.jsx
Added buttons to the profile page that allow the user to delete or edit room.
=> Added delete/edit room buttons

package-lock.json, package.json, src/main.jsx, src/store.js
Installed Redux persist. Still one unidentified error.
=> Started Redux Persist

src/App.jsx, src/Pages/Components/AddPeices.css, src/Pages/Components/AddPeices.jsx, src/Pages/Components/AddPlayer.css, src/Pages/Components/AddPlayer.jsx, src/Pages/Components/CreateScene.jsx, src/Pages/Components/Pieces.jsx, src/Pages/Components/Player.jsx, src/Pages/Components/Scenes.css, src/Pages/Components/Scenes.jsx, src/Pages/Components/pieces.css, src/Pages/Components/player.css
finished x buttons on all pop ups on the rooms page and added the add player popup
=> finished x buttons

src/Pages/ProfilePage.jsx
=> end of day

package-lock.json, package.json, src/Pages/Components/Pieces.jsx, src/Pages/Components/pieces.css
=> framerMotion

src/Pages/Components/AddPeices.jsx, src/Pages/Components/AddPlayer.jsx, src/Pages/Components/CreateScene.jsx, src/Pages/Components/FunctionButtons.jsx, src/Pages/Components/Pieces.jsx, src/Pages/Components/Player.jsx, src/Pages/Components/Scenes.jsx, src/Pages/Rooms.jsx, src/Reducers/AddPlayerPopupSlice.js, src/Reducers/showAddPiecePopupSlice.js, src/Reducers/showCreateScenePopupSlice.js, src/Reducers/showResourcePopupSlice.js, src/Reducers/showScenePopupSlice.js, src/store.js
So you can close them with the x button.
=> Room popups are now in Redux store

src/Pages/LoginPage.jsx, src/Pages/SignUpPage.jsx
...in addition to pressing the existing buttons.
=> Allow login/sign up vie enter

src/Pages/Components/AddPeices.jsx, src/Pages/Components/AddPlayer.jsx, src/Pages/Components/CreateScene.jsx, src/Pages/Components/Scenes.jsx, src/Pages/Home.css, src/Pages/HomePage.jsx, src/Pages/ProfilePage.jsx, src/Pages/Rooms.css, src/Pages/Rooms.jsx
changes to the room page and centered the profile page
=> small bug changes

src/Pages/Components/Pieces.jsx, src/Pages/Components/pieces.css, src/Pages/Rooms.css
changed css on pieces and rooms
=> small changes on css

src/Pages/Rooms.jsx
added multiple pieces to board but cant add 2 at the same time of the same kind
=> added multiple peices

src/Pages/ProfilePage.jsx, src/Pages/Rooms.jsx, src/Reducers/PieceToDropSlice.js, src/store.js
Also drop the pieces in the center of the map now
=> Putting pieces to drop in Redux

src/Pages/ProfilePage.jsx
made a loop to add through a array of objects
=> dynamic names and rooms

src/Pages/Components/Pieces.jsx, src/Reducers/PieceToDropSlice.js
Some instructions for the boys
=> To-do instructions

src/Pages/Components/EditProfile.jsx, src/Pages/ProfilePage.jsx
-You can now edit profile from the UI.
-Now shows "no rooms yet!" message.
=> Various backend changes on Profile.jsx

src/Pages/Components/Pieces.jsx, src/Pages/LoginPage.jsx, src/Pages/ProfilePage.jsx, src/Pages/Rooms.css, src/Pages/Rooms.jsx, src/Pages/SignUpPage.jsx
big fixes on profile page and on the rooms page
=> some bug fixing

src/Pages/CreateRoom.jsx, src/Pages/EditRoom.jsx
...with the backend.
-You can create a room from the UI
-You can almost edit a room from the UI (still need to work in roomID somewhere).
=> Making the popups on Profile work

src/App.jsx, src/Pages/Components/EditProfile.jsx, src/Pages/CreateRoom.jsx, src/Pages/EditRoom.jsx, src/Pages/HomePage.jsx, src/Pages/ProfilePage.jsx, src/store.js
Combined the User and Room Redux state into a single state called persistedReducer with the keys `user` and `room`. Changed any useSelectors that reference those states.
=> Setting up nested persists

src/Pages/Components/Pieces.jsx, src/Pages/Rooms.jsx
got all tokens showing up on the screen and styled
=> tokens working

src/Pages/Components/Pieces.jsx, src/Pages/Rooms.jsx
animation done on some bars on load on room page. may or may not keep
=> animations

src/Pages/Components/EditProfile.jsx, src/Pages/Components/Player.jsx, src/Pages/ProfilePage.jsx
-Clicking on a room properly puts that room in Redux state. -The users in a given room now properly display.
=> viewUsers bug fix

src/Pages/Components/AddPeices.jsx, src/Pages/Components/Pieces.jsx, src/Pages/Components/Player.jsx
-Resources now load from the database instead of a static array. -You can now add resources from the UI
-Movement of resources still functions properly and has not changed.
=> Fetching resources from the database

src/Pages/Components/Pieces.jsx, src/Pages/Rooms.jsx, src/Reducers/PieceToDropSlice.js
Properly, using a new field called key which is separate from ID.
=> Resources are deleted from the board

src/Pages/Components/Pieces.jsx, src/Pages/Rooms.css, src/Pages/Rooms.jsx
added delete buttons and animations to them accoringly
=> added buttons

src/Pages/Components/Player.jsx, src/Pages/Components/player.css, src/Reducers/PlayersDropMenu.js, src/store.js
=> drop menu on room page player

src/Pages/Components/Pieces.jsx, src/Pages/Components/Scenes.css, src/Pages/Components/Scenes.jsx, src/Pages/Components/pieces.css, src/Pages/HomePage.jsx, src/Pages/Rooms.css
did small updates on the main page making it prettier changed background color on the rooms page
=> did small updates

src/Pages/Components/Player.jsx
Need to redploy to test new route that should remove player from room without deleting them from the DB
=> Going home and switching computers

src/Pages/Components/EditProfile.jsx, src/Pages/ErrorPage.jsx, src/Pages/Rooms.jsx
=> mobile fixes

src/Pages/Components/Player.jsx, src/Pages/CreateRoom.jsx, src/Pages/ProfilePage.jsx, src/Reducers/ReloadRoomsSlice.js, src/store.js
successful, but new bug where delete needs to be hit 2x before room deletes
=> working on reloading rooms on create and delete

src/Pages/ProfilePage.jsx
=> forgot this

src/Pages/ProfilePage.jsx
technically you don't need to dispatch the room on the delete button anymore but.... whatever
=> Room deleting bug fixing

src/Pages/Components/FunctionButtons.jsx, src/Pages/EditRoom.jsx, src/Pages/HomePage.jsx, src/Pages/LoginPage.jsx
changed some of the ui on profile page
=> small ui changes

src/Pages/Components/Pieces.jsx, src/Pages/Components/pieces.css, src/Pages/Rooms.css
updates the sizing of the bottom pieces to fit mobile
=> more styling to the mobile view

src/Pages/Rooms.css
=> updated height for mobile... again

src/Pages/Components/Player.jsx, src/Pages/CreateRoom.jsx, src/Pages/ProfilePage.jsx
=> small grab bag

index.html, src/Pages/signup.css
=> added font

src/WebSocket.jsx
URLs changed to deployed URLs instead of localhost.
=> Deployment changes
